export const categories = [
  { id: 'life-diary', label: 'Diario de Vida' },
  { id: 'health', label: 'Salud' },
  { id: 'work', label: 'Trabajo' },
  { id: 'study', label: 'Estudio' },
  { id: 'social', label: 'Social' },
  { id: 'hobby', label: 'Pasatiempos' },
  { id: 'travel', label: 'Viajes' },
  { id: 'food', label: 'Comida' },
  { id: 'sports', label: 'Deportes' },
  { id: 'entertainment', label: 'Entretenimiento' },
  { id: 'other', label: 'Otros' },
  { id: 'fitness', label: 'Fitness' },
  { id: 'meditation', label: 'Meditación' },
  { id: 'reading', label: 'Lectura' },
  { id: 'writing', label: 'Escritura' },
  { id: 'art', label: 'Arte' },
  { id: 'music', label: 'Música' },
  { id: 'family', label: 'Familia' },
  { id: 'friends', label: 'Amigos' },
  { id: 'dating', label: 'Citas' },
  { id: 'eat', label: 'Comida' },
]; 